### ISSUE TITLE
Credit Currency attributes are missing

### ISSUE THREAD

**Issue by joeharris76** [elucid/ruby-freshbooks#1]
[First of all - thanks for the library! Vastly superior to freshbooks.rb for my purposes.]

The Client part of the API includes a Credits element that replaces the deprecated Credit element. Unfortunately Credits includes a Currency attribute that is not being picked up. This is an oddity in their implementation really because it's not done anywhere else.

The XML is:
      <credits>
        <credit currency="GBP">100</credit>
        <credit currency="USD">150</credit>
      </credits>

This is what ruby-freshbooks _currently_ returns:
            "credits" => {
                "credit" => ["100", "150"]
            }

And what I think ruby-freshbooks _should_ return:
            "credits" => [{
                "credit" => "100",
                "currency" => "GBP"
                },
                {"credit" => "150",
                 "currency" => "USD"
                }]

I'm looking for a solution at the minute but, frankly, I'm not entirely grokking some of the magic so if you have any ideas please let me know.

Thanks,
Joe

**Comment by joeharris76** [comment]
Hmm, I tracked this down. The parsing is done in HTTParty by the Crack gem. As per the tests in that library this is the intended behaviour. Exactly _why_ they would intend this is not clear to me but the attribute is retained and can be retrieved using the #attributes method - ['client']['credits']['credit'][0].attributes

**Comment by elucid** [comment]
That's right.

I'm not sure if I agree with representing the attributes in this manner, but at least they're available.

I don't think that I agree with your proposed representation either--structurally `currency="GBP"` is a child of the `<credit>` node. In your representation they're siblings.

Anyhow, this is a common problem with parsing XML into simple dictionary/list composite data structures. All of the different alternatives are slightly awkward and I've never seen one that I really like.

**Comment by joeharris76** [comment]
Thanks for the reply. You're right, currency should probably be a child of credit.

I agree with you about XML parsing being a bit of a pain. I went a good way down the road with HappyMapper but it wasn't really the right approach. Since this is the only place FB use an attribute as a meaningful value it's not a problem.
